"""add_multi_branch_support

Revision ID: f59810d75dca
Revises: 20260525_02
Create Date: 2026-05-25 18:41:50.630731

"""
from typing import Sequence, Optional

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f59810d75dca'
down_revision: Optional[str] = '20260525_02'
branch_labels: Optional[Sequence[str]] = None
depends_on: Optional[Sequence[str]] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=True)
    op.drop_constraint(op.f('clients_document_id_key'), 'clients', type_='unique')
    op.drop_index(op.f('ix_clients_document_id'), table_name='clients')
    op.create_index(op.f('ix_clients_document_id'), 'clients', ['document_id'], unique=True)
    op.alter_column('invoices', 'dian_status',
               existing_type=postgresql.ENUM('pending', 'accepted', 'rejected', name='dian_status_enum'),
               type_=sa.Enum('pending', 'accepted', 'rejected', name='dianstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::dian_status_enum"))
    op.add_column('products', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('products_barcode_key'), 'products', type_='unique')
    op.drop_constraint(op.f('products_code_key'), 'products', type_='unique')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_branch_id'), 'products', ['branch_id'], unique=False)
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.create_foreign_key(None, 'products', 'branches', ['branch_id'], ['id'])
    op.drop_column('purchase_order_items', 'received_quantity')
    op.add_column('purchase_orders', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.add_column('purchase_orders', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('purchase_orders', sa.Column('total', sa.Float(), nullable=False))
    op.alter_column('purchase_orders', 'status',
               existing_type=postgresql.ENUM('pending', 'sent', 'received', name='order_status_enum'),
               type_=sa.Enum('pending', 'sent', 'received', name='orderstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status_enum"))
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_purchase_orders_branch_id'), 'purchase_orders', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'purchase_orders', 'branches', ['branch_id'], ['id'])
    op.drop_column('purchase_orders', 'order_date')
    op.drop_column('purchase_orders', 'expected_date')
    op.drop_column('purchase_orders', 'received_date')
    op.drop_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.add_column('sales', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.alter_column('sales', 'payment_method',
               existing_type=postgresql.ENUM('cash', 'card', 'credit', 'nequi', name='payment_method_enum'),
               type_=sa.Enum('cash', 'card', 'credit', 'nequi', name='paymentmethod'),
               existing_nullable=False)
    op.create_index(op.f('ix_sales_branch_id'), 'sales', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'branches', ['branch_id'], ['id'])
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_pin_code_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    op.add_column('vehicles', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_vehicles_branch_id'), 'vehicles', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'branches', ['branch_id'], ['id'])
    op.create_index(op.f('ix_work_order_services_id'), 'work_order_services', ['id'], unique=False)
    op.add_column('work_orders', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.alter_column('work_orders', 'status',
               existing_type=postgresql.ENUM('scheduled', 'in_progress', 'completed', 'cancelled', name='work_order_status_enum'),
               type_=sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='workorderstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::work_order_status_enum"))
    op.create_index(op.f('ix_work_orders_branch_id'), 'work_orders', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'work_orders', 'branches', ['branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_index(op.f('ix_work_orders_branch_id'), table_name='work_orders')
    op.alter_column('work_orders', 'status',
               existing_type=sa.Enum('scheduled', 'in_progress', 'completed', 'cancelled', name='workorderstatus'),
               type_=postgresql.ENUM('scheduled', 'in_progress', 'completed', 'cancelled', name='work_order_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'scheduled'::work_order_status_enum"))
    op.drop_column('work_orders', 'branch_id')
    op.drop_index(op.f('ix_work_order_services_id'), table_name='work_order_services')
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_branch_id'), table_name='vehicles')
    op.drop_column('vehicles', 'branch_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_pin_code_key'), 'users', ['pin_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'branch_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_branch_id'), table_name='sales')
    op.alter_column('sales', 'payment_method',
               existing_type=sa.Enum('cash', 'card', 'credit', 'nequi', name='paymentmethod'),
               type_=postgresql.ENUM('cash', 'card', 'credit', 'nequi', name='payment_method_enum'),
               existing_nullable=False)
    op.drop_column('sales', 'branch_id')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('refresh_tokens_token_key'), 'refresh_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.add_column('purchase_orders', sa.Column('received_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('expected_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('purchase_orders', sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_orders_branch_id'), table_name='purchase_orders')
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.Enum('pending', 'sent', 'received', name='orderstatus'),
               type_=postgresql.ENUM('pending', 'sent', 'received', name='order_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::order_status_enum"))
    op.drop_column('purchase_orders', 'total')
    op.drop_column('purchase_orders', 'date')
    op.drop_column('purchase_orders', 'branch_id')
    op.add_column('purchase_order_items', sa.Column('received_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_index(op.f('ix_products_branch_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_unique_constraint(op.f('products_code_key'), 'products', ['code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('products_barcode_key'), 'products', ['barcode'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'branch_id')
    op.alter_column('invoices', 'dian_status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', name='dianstatus'),
               type_=postgresql.ENUM('pending', 'accepted', 'rejected', name='dian_status_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::dian_status_enum"))
    op.drop_index(op.f('ix_clients_document_id'), table_name='clients')
    op.create_index(op.f('ix_clients_document_id'), 'clients', ['document_id'], unique=False)
    op.create_unique_constraint(op.f('clients_document_id_key'), 'clients', ['document_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
